### ISSUE TITLE
Subscribing to all messages with # returns the topic # on the decode publish package

### ISSUE THREAD

**Issue by russellgsystems** [LabVIEW-Open-Source/LV-MQTT-Broker#150]
I really like this toolkit, but I found that if I try to subscribe to all topics using # then all of the packages decoded always have the topic # instead of the specific one that was returned. In order to get the specific topic I had to explicitly subscribe to each topic.  see the images below.

![Subscribe to All Topics](https://user-images.githubusercontent.com/68344965/91164976-8e4abe00-e695-11ea-9f79-5f40f9b7dce5.png)
![Subscribe to Specific Topics](https://user-images.githubusercontent.com/68344965/91164987-9145ae80-e695-11ea-9143-2b070d6631a3.png)

**Comment by francois-normandin** [comment]
@russellgsystems I have been aware of this for a while and never got around to look into it, but I now consider it to be high-priority. It is related to some features that are not yet implemented in section 3-4, but this can be fixed without waiting for the publish packet to be feature complete.
I think it's a low hanging fruit to gain lots of functionality...

**Comment by russellgsystems** [comment]
@francois-normandin thank you so much I really appreciate it. For now we can just explicitly subscribing to the topics so we have a workaround but it would be nice to be able to just subscribe to all topics. Thank you again!

**Comment by francois-normandin** [comment]
Issue reproduced and Unit Test 3.3.2-3 now properly fails.
![image](https://user-images.githubusercontent.com/11728548/91365010-1a600100-e7ce-11ea-96a0-e0b8e8aeb683.png)

**Comment by francois-normandin** [comment]
This is fixed and will be part of the next released package.
![image](https://user-images.githubusercontent.com/11728548/91365633-9575e700-e7cf-11ea-805e-e4b3d72a6ac3.png)

**Comment by russellgsystems** [comment]
I am glad it was an easy fix. Thank you!

**Comment by francois-normandin** [comment]
Fixed and released in 1.0.4
