### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by hildogjr** [LabVIEW-Open-Source/LV-MQTT-Broker#155]
This report is more like a need for user help.

I am trying to open the library code in a LabVIEW 19.0f2 (32-bits) e getting a problem when try to load the "Serializer.lvclass".

Do I need to install the *.vip files? They have to be executed on "JKI VI Package Manager"?

![image](https://user-images.githubusercontent.com/2211474/95254001-a285ed00-07f5-11eb-81be-1b2bd0241c43.png)

**Comment by francois-normandin** [comment]
@hildogjr 
If you are running from source, you must "apply" the VI Package Configuration to install dependencies.
Look for the file: "MQTT Broker.vipc" at the root
Once you have the dependencies, you should be able to open the project.

If you want to install the latest package in the palette, you indeed need to install through the VIP file found in the release.

**Comment by francois-normandin** [comment]
closing this issue.
Please re-open if the problem was not fixed with applying the vipc file.

I'll soon deploy those libraries on the VIPM Community repository, which should make it quite simple to follow and keep track of dependencies.

**Comment by hildogjr** [comment]
Thanks, I just had to attempt some times to the requirements were successfully downloaded.
