### ISSUE TITLE
MIgration of MQTT Broker project in sub-projects

### ISSUE THREAD

**Issue by francois-normandin** [LabVIEW-Open-Source/LV-MQTT-Broker#156]
I'm in the process of splitting the code into smaller chunks and organize it under a new palette.
As mentioned in this post: 
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/153#issuecomment-712319246

This effort is underway and I'm opening this ticket to keep anyone interested in this development aware of the status of this migration. If you have questions, please don't hesitate.

The project is being broken down into small chunks and you can keep track of all those below: 
- https://github.com/LabVIEW-Open-Source/LV-MQTT-Control-Packets
- https://github.com/LabVIEW-Open-Source/MQTT-Connection
- https://github.com/LabVIEW-Open-Source/MQTT-Connection-LocalQueue
- https://github.com/LabVIEW-Open-Source/MQTT-Connection-TCP
- https://github.com/LabVIEW-Open-Source/MQTT-Connection-Websockets
- https://github.com/LabVIEW-Open-Source/MQTT-Client
- https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker

The tasks ahead to complete this migration are: 

- Transfer the unit tests from the broker to more suitable sub-project
- Harmonize the error codes of the Websockets and Local Queue connection objects with the TCP Connection object
- Fix the slowdown with launching clients that occurred during the transfer (yet unexplained, related to access scope or re-entrancy settings... somehow)
- Release the packages on the VIPM Community repository
- Provide documentation on the changes

There will be one important change for the client and server, and it's to do with the connector pane of the object creation and connection methods: The connection method will no longer accept the arguments for connection, since it will now be abstracted into a generic connection type. From now on, the connection configuration will be injected in the constructor method.

The change will be very easy to fix and not require a whole lot of work. This will be part of the documentation.

For now, you are free to play with the new building blocks. It is likely that the error codes for the "Connection" class and its children classes will change, but their API should stay the same.

**Comment by francois-normandin** [comment]
Task Update

* Transfer the unit tests from the broker to more suitable sub-project **(DONE, all tests will stay in broker repository for now)**
* Harmonize the error codes of the Websockets and Local Queue connection objects with the TCP Connection object **DONE**
* Fix the slowdown with launching clients that occurred during the transfer (yet unexplained, related to access scope or re-entrancy settings... somehow) **Will investigate, but not an issue for normal operation** 
* Release the packages on the VIPM Community repository **DONE, last packages are in the pipeline for publication today**
* Provide documentation on the changes

**Comment by jkoplo** [comment]
I left some feedback in another thread (https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/158#issuecomment-717378368). I'd be more than willing to combine efforts and help develop the MQTT Client - I have a pretty immediate need for a good client implementation and have started my own fork of another project.

That being said, I'm not sure that splitting the project into a ton of separate repos is conducive to community development. I know you're already down this path, but maybe consider having a clear set of instructions for pulling all dependencies in the proper order? Or maybe include dependencies for the user facing libraries (Client/Server) as git submodules to simplify the development environment?

**Comment by francois-normandin** [comment]
Great feedback.

I've added a "Full.Project.Dependencies.vipc" under the assets of the latest release. I'll do this from now on.
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/releases/tag/3.1.2

Simply put, this VIPC file will contain all the necessary dependencies to open the MQTT Broker lvproj file, even if those dependencies are not yet available on the VIPM Community repository.

A Wiki page has been created to clarify instructions:

https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/wiki/HOW-TO:-Setup-your-IDE-to-run-this-project-from-source
