### ISSUE TITLE
QoS = 2 subscription causes a disconnection by peer error (code 66)

### ISSUE THREAD

**Issue by francois-normandin** [LabVIEW-Open-Source/LV-MQTT-Broker#162]
(details upcoming)

**Comment by francois-normandin** [comment]
To reproduce: A client subscribes to any topic with a QoS = 2. The client receives one application message and then the connection is closed with Error 66 (disconnected by peer). 
Problem is likely in the PUBREL/PUBCOMP transaction where the server session terminates prematurely in the verification of acknowledgements.

Note to self: check the symmetry of the QoS = 2 publication logic in both Client-to-Server and Server-to-Client directions.

**Comment by russellgsystems** [comment]
@francois-normandin thank again for all your help with troubleshooting this.  Whenever I try to use Qos=2 I get

"Error 56 occurred at MQTT Client.lvlib:Client.lvclass:SendPacket.vi:1460007

Possible reason(s):

No connection"

Do you think that is related to error 66?

**Comment by francois-normandin** [comment]
@russellgsystems Yes I think they are related. I've just started investigating today. So far, I see that the client sometimes receives a malformed packet in the QoS=2 exchange.

The client's session is stopping on this error: 
> Error 55001 occurred at MQTT_Control_Packets.lvlib:PUBREC.lvclass:Validate Fixed Header.vi:4720001
> Possible reason(s): malformed packet

That would tell me that the server is generating a bad packet, or the client does not put it together correctly... unless it is simply a Control Packet bug.

**Comment by francois-normandin** [comment]
I found the issue. The Server's subscription process attempts to resend duplicate packets (with DUP flag) and there is a bug with this feature. Since the DUP is not yet supported by unit testing, I will disable it until full implementation. Looks like the operation for flipping the DUP flag is incorrect and results in the transmission of a malformed packet. The resulting disconnection is consistent with the expected behavior in such cases.

**Comment by francois-normandin** [comment]
Fixed and released in 3.1.4

**Comment by russellgsystems** [comment]
Thanks that fixed the problem was seeing with Qos=2.
