### ISSUE TITLE
Broken VI when dropping a template from the MQTT Client palette.

### ISSUE THREAD

**Issue by Febronie** [LabVIEW-Open-Source/LV-MQTT-Broker#170]
![image](https://user-images.githubusercontent.com/91299595/134614555-b1c71aac-d16c-4613-882f-bb3e43c880ce.png)
[Doc1.docx](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/7222140/Doc1.docx)

**Comment by francois-normandin** [comment]
Can you hit the Run arrow, or press Ctrl-L, to show the verbose list of errors?

![Screenshot_20210924-061339.png](https://user-images.githubusercontent.com/11728548/134658713-dd60e684-bcce-4a54-bdf2-664f589280d3.png)

**Comment by Febronie** [comment]
![image](https://user-images.githubusercontent.com/91299595/134697282-6784f626-6d31-4416-b8eb-51df0bf0b501.png)

**Comment by Febronie** [comment]
![image](https://user-images.githubusercontent.com/91299595/134697526-e1e77930-7f4c-469d-8c63-18111794b612.png)

**Comment by Febronie** [comment]
Hello,I did it and sceenshot has already posted on GitHub

**Comment by francois-normandin** [comment]
There is not enough information to help you. Please find the broken part. The screenshot you provided shows that the VI is fine. One of the subVI is broken. 

I've been using this code for months in production. I know it works fine. You will need to find the VI that is broken and display its block diagram. Until you give more information, it is impossible to help you.

Also, please provide environment configuration. Which LabVIEW version are you using? What packages are installed on VIPM? Are you on 32-bit it 64-bit?

**Comment by Febronie** [comment]
I use Labview 2020, and VI is 32.

**Comment by Febronie** [comment]
Labview 2020 sp1 64 bit and about the installed package in vi may be i can
take a Screen shoot

**Comment by francois-normandin** [comment]
@Febronie Can you apply the filter "LabVIEW Open Source" in VIPM to remove all other packages from the list?
It will allow me to help you debug a bit further and determine if it's a bug with the 64-bit version of the package or a problem specific to your machine.

This is what I need to install the same package stack as on your machine and reproduce the issue reported.
![image](https://user-images.githubusercontent.com/11728548/134774917-bb86f2e2-1f01-4d81-9f9d-61a0965479b7.png)

**Comment by francois-normandin** [comment]
I have just tested with these two LabVIEW versions and they both worked:
- LabVIEW 2018 64-bit
- LabVIEW 2020 32-bit

I don't have LV2020 64-bit on any of my systems, but I doubt very much that this would be an issue. These libraries are all 100% written in LabVIEW so they remain cross-platform and independent of OS, realtime target or bitness.

My advice is to uninstall the packages, close LabVIEW and re-install them again. Start from a clean slate and make sure to allow mass compile to complete at the end of the package installation.

**Comment by Febronie** [comment]
Hello,I have installed everything inVI package and installed again now i
see the previous issue is not appearing.now i can drop the MQTT VI and it
came without any error.Thank you very much for helping ,accompanying and
much effort you provided for to get it here.i really appreciate it.
