### ISSUE TITLE
Last Will messages

### ISSUE THREAD

**Issue by MikeWebsterGenuen** [LabVIEW-Open-Source/LV-MQTT-Broker#174]
Hey,  I was wondering if the last will messages were supposed to work.  I have them as part of the client connection.  I see the publication of 'online' to the topic when it starts, but when I pull the plug (hitting the stop button on the client machine), I see nbConnections decrement on the Server, but the will message is never published.  Do I have something out of order?  I've tried several combinations of Will Retain, Will QOS 1, Will Flag and decreasing the Keep Alive.

![image](https://user-images.githubusercontent.com/105722691/180860860-763c2f5f-7385-405b-aaad-3e5021c584cf.png)

**Comment by francois-normandin** [comment]
@MikeWebsterGenuen 
Not yet.
This is a feature I have not yet started working on. 

for reference, you can look into the 3.1.2-x issues (all still opened).

https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/19
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/20
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/21
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/22
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/23
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/24
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/25
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/26
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/27
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/28
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/45

**Comment by MikeWebsterGenuen** [comment]
Thanks for the quick reply.  I'll just write like an incrementing watchdog message instead.
