### ISSUE TITLE
Retain published data

### ISSUE THREAD

**Issue by ibmartinez** [LabVIEW-Open-Source/LV-MQTT-Broker#175]
Hello!

I am trying to publish data with a LabVIEW MQTT Client with the retain flag set to true. If I use non LabVIEW Brokers like Mosquitto, everything works perfect, the last values are retained and available for other clients.

However if I use the LabVIEW broker provided by these libraries, the retain property does not work. Last values are not stored in the broker.

I would like to know if there is any possibility to use the LabVIEW MQTT Broker with the retain porperty.

Thanks in advance for your time.

**Comment by francois-normandin** [comment]
Hello @ibmartinez ,

The MQTT broker does not yet implement those features.

All RETAIN requirements are part of sections 3.1.1 and 3.1.2 off the specification. Add of today, the LV broker does not implement them. You can refer to issues with this filter:

https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues?q=is%3Aissue+is%3Aopen++retain+

**Comment by ibmartinez** [comment]
Hello,

Thank you for your quick answer.

Hopefully we can use the retain property with a LabVIEW Broker in the future! 
Thank you again for your work
