### ISSUE TITLE
Error 66 is being sent by client connect vi in labview

### ISSUE THREAD

**Issue by zombae98** [LabVIEW-Open-Source/LV-MQTT-Broker#182]
Hi i am using MQTT to publish data onto systemlink cloud. I am using  a esp32(publisher), raspberry pi(broker and susbsciber), mosquitto mqtt broker. I am successful in getting the data from the esp32 to the broker but i am having trouble configuring the raspberry pi in LabVIEW to get the data from the mosquitto as a subscriber. I keep on getting error 63 and error 66 when i try and connect to the broker. I am using the MQTT VI available on the VIPM. I have used localhost and the ip address as my TCP connect configuration to connect to the server, i am also  passing the username and password as a cluster in the connect to server VI. I am also running LV 2021 CE and makerhub to connect and deploy my application.
![rpi4](https://user-images.githubusercontent.com/127276587/223616814-f90482b5-150c-4f16-a8d2-55c3dac46c32.jpg)
![rpi1](https://user-images.githubusercontent.com/127276587/223616833-bdd1f8fc-604f-454b-a71f-9850f35d7058.jpg)
![rpi2](https://user-images.githubusercontent.com/127276587/223616836-58c46deb-bf9d-4161-bad5-b4545340d83a.jpg)
![rpi3](https://user-images.githubusercontent.com/127276587/223616839-55ed5adb-daa1-4e6d-a149-c1aa30ffa800.jpg)
you can refer to the NI forum Post where I have posted the issue https://forums.ni.com/t5/LabVIEW/MQTT-Labview/m-p/4288140#M1251469

**Comment by francois-normandin** [comment]
Error 66 is a response that means "Socket has been closed by the peer". It can be the result of a protocol violation, failure to identify, incorrect connection flags, etc.

If you think this is not a normal response, can you share details about the issue? And if possible, with example code.

**Comment by zombae98** [comment]
> Error 66 is a response that means "Socket has been closed by the peer". It can be the result of a protocol violation, failure to identify, incorrect connection flags, etc.
> 
> If you think this is not a normal response, can you share details about the issue? And if possible, with example code.

I am using the default drop in simple connection VI

**Comment by zombae98** [comment]
HI forgot to mention when i connect to my windows broker it works fine but gives out this error when i try and connect to the raspberry pi broker. Below is a snapshot of my code if it helps. I do enter my username and password but i have left that out 
![image](https://user-images.githubusercontent.com/127276587/223617612-7b600996-b3d3-4f48-a833-b4dfc0e9643e.png)
![image](https://user-images.githubusercontent.com/127276587/223617661-39e91564-8c2c-4d06-848d-41eedcab218b.png)
![image](https://user-images.githubusercontent.com/127276587/223617818-158f047d-7f2d-45f3-afaa-181e90d19c6f.png)

**Comment by francois-normandin** [comment]
If you enter both username and password, are you also checking both flags?

![image](https://user-images.githubusercontent.com/11728548/223619187-e732fca4-523e-4cd5-9535-756e373c66ac.png)

**Comment by zombae98** [comment]
> If you enter both username and password, are you also checking both flags?
> 
> ![image](https://user-images.githubusercontent.com/11728548/223619187-e732fca4-523e-4cd5-9535-756e373c66ac.png)

NO

**Comment by zombae98** [comment]
> If you enter both username and password, are you also checking both flags?
> 
> ![image](https://user-images.githubusercontent.com/11728548/223619187-e732fca4-523e-4cd5-9535-756e373c66ac.png)
Its working now 
Thanks for the help you have been awesome

**Comment by francois-normandin** [comment]
Glad it worked out.
